apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-eks-test
  namespace: default
  labels:
    cluster.x-k8s.io/managed-by: rancher
    cluster-api.cattle.io/rancher-auto-import: "true"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  topology:
    class: my-eks-test-class-v2
    version: v1.31.0
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 3

