# --- VERSIONED CONTROL PLANE ---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlaneTemplate
metadata:
  name: eks-control-plane-v1-34
  namespace: default
spec:
  template:
    spec:
      version: v1.34.0
      region: us-east-1
      sshKeyName: default-key
      associateOIDCProvider: false
      endpointAccess:
        public: true
        private: true
      # This configuration populates the aws-auth ConfigMap
      iamAuthenticatorConfig:
        mapRoles:
          - rolearn: "arn:aws:iam::058264532137:role/nodes.cluster-api-provider-aws.sigs.k8s.io"
            username: "system:node:{{EC2PrivateDNSName}}"
            groups:
              - system:bootstrappers
              - system:nodes
        mapUsers:
          - userarn: "arn:aws:iam::058264532137:user/emendonca-remote"
            username: admin
            groups:
              - system:masters
      addons:
        - name: aws-ebs-csi-driver
          version: v1.58.0-eksbuild.1
          conflictResolution: overwrite
        - name: coredns
          version: v1.12.3-eksbuild.1
          conflictResolution: overwrite
        - name: kube-proxy
          version: v1.34.0-eksbuild.2
          conflictResolution: overwrite
        - name: vpc-cni
          version: v1.20.4-eksbuild.2
          conflictResolution: overwrite
---
# --- MACHINE TEMPLATE: MEDIUM (v1-34) ---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: worker-v1-34-medium
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: default-key
      ami:
        id: ami-00b16894e17387eb9
---
# --- MACHINE TEMPLATE: LARGE (v1-34) ---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: worker-v1-34-large
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.large
      sshKeyName: default-key
      ami:
        id: ami-00b16894e17387eb9
---
# --- MACHINE TEMPLATE: XLARGE (v1-34) ---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: worker-v1-34-xlarge
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.xlarge
      sshKeyName: default-key
      ami:
        id: ami-00b16894e17387eb9
---
# --- CLUSTER CLASS: MEDIUM (v1-34) ---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: eks-v1-34-medium
  namespace: default
spec:
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSManagedClusterTemplate
      name: cluster-fixed
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: AWSManagedControlPlaneTemplate
      name: eks-control-plane-v1-34
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
              kind: EKSConfigTemplate
              name: bootstrap-fixed
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
              kind: AWSMachineTemplate
              name: worker-v1-34-medium
---
# --- CLUSTER CLASS: LARGE (v1-34) ---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: eks-v1-34-large
  namespace: default
spec:
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSManagedClusterTemplate
      name: cluster-fixed
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: AWSManagedControlPlaneTemplate
      name: eks-control-plane-v1-34
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
              kind: EKSConfigTemplate
              name: bootstrap-fixed
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
              kind: AWSMachineTemplate
              name: worker-v1-34-large
---
# --- CLUSTER CLASS: XLARGE (v1-34) ---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: eks-v1-34-xlarge
  namespace: default
spec:
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSManagedClusterTemplate
      name: cluster-fixed
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: AWSManagedControlPlaneTemplate
      name: eks-control-plane-v1-34
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
              kind: EKSConfigTemplate
              name: bootstrap-fixed
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
              kind: AWSMachineTemplate
              name: worker-v1-34-xlarge
---
